<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Goo.GL</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <form method="post" action="/urlshortener">
                <div class="form-group">
                    <label for="exampleInputEmail1">Your Link</label>
                    <input type="url" name="url" class="form-control">
                </div>
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
        </div>
    </div>
</div>
</body>
</html>